apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourcequota.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  hard:
    requests.cpu: {{ .Values.resourcequota.requests.cpu }}
    requests.memory: {{ .Values.resourcequota.requests.memory }}
    limits.cpu: {{ .Values.resourcequota.limits.cpu }}
    limits.memory: {{ .Values.resourcequota.limits.memory }}
