apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.appLabel }}
    spec:
      automountServiceAccountToken: {{ .Values.statefulset.automountServiceAccountToken }}
      containers:
      - name: demon-box
        image: {{ .Values.statefulset.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 5000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: {{ .Values.statefulset.resources.requests.memory }}
            cpu: {{ .Values.statefulset.resources.requests.cpu }}
          limits:
            memory: {{ .Values.statefulset.resources.limits.memory }}
            cpu: {{ .Values.statefulset.resources.limits.cpu }}
  volumeClaimTemplates:
  - metadata:
      name: orbiter-module
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: bordeaux
