apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bordeaux 
provisioner: kubernetes.io/gce-pd  
parameters:
  type: pd-ssd  
  replication-type: none
reclaimPolicy: Delete  
allowVolumeExpansion: true 

